# Custom Language File for Launcher Customizer

[ejs.app]
title = "Dystopian Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Dystopian"
welcomeDescription = "L'équipe de souhaite un bon jeu"
welcomeDescCTA = "You are just a few clicks away from Westeros."
