# Custom Language File for Launcher Customizer

[ejs.app]
title = "Dystopian Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/CronaG/apocalyptic-survival-launcher-electron-version"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@Crona-q4k"
mediaDiscordURL = "https://discord.gg/hrqdBvnPAv"

[ejs.settings]
sourceGithubLink = "https://github.com/CronaG/apocalyptic-survival-launcher-electron-version"
supportLink = "https://github.com/CronaG/apocalyptic-survival-launcher-electron-version/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Dystopian"
welcomeDescription = "L'équipe de souhaite un bon jeu"
welcomeDescCTA = "You are just a few clicks away from Westeros."
